export const SET_FILTERS_MODAL_OPEN: "SET_FILTERS_MODAL_OPEN" =
  "SET_FILTERS_MODAL_OPEN";

export const GET_PLAYERS_REQUEST: "GET_PLAYERS_REQUEST" = "GET_PLAYERS_REQUEST";
export const GET_PLAYERS_SUCCESS: "GET_PLAYERS_SUCCESS" = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_FAILED: "GET_PLAYERS_FAILED" = "GET_PLAYERS_FAILED";
