export const SET_MODAL_OPEN: "SET_MODAL_OPEN" = "SET_MODAL_OPEN";

export const SET_GENDER: "SET_GENDER" = "SET_GENDER";
export const SET_AGE: "SET_AGE" = "SET_AGE";
export const SET_SUBJECT_RF: "SET_SUBJECT_RF" = "SET_SUBJECT_RF";
export const SET_SEARCH: "SET_SEARCH" = "SET_SEARCH";
export const APPLY_FILTERS: "APPLY_FILTERS" = "APPLY_FILTERS";
export const DELETE_FILTER: "DELETE_FILTER" = "DELETE_FILTER";
export const CLEAR_FILTERS: "CLEAR_FILTERS" = "CLEAR_FILTERS";

export const GET_PLAYERS_REQUEST: "GET_PLAYERS_REQUEST" = "GET_PLAYERS_REQUEST";
export const GET_PLAYERS_SUCCESS: "GET_PLAYERS_SUCCESS" = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_FAILED: "GET_PLAYERS_FAILED" = "GET_PLAYERS_FAILED";

export const GET_PLAYER_REQUEST: "GET_PLAYER_REQUEST" = "GET_PLAYER_REQUEST";
export const GET_PLAYER_SUCCESS: "GET_PLAYER_SUCCESS" = "GET_PLAYER_SUCCESS";
export const GET_PLAYER_FAILED: "GET_PLAYER_FAILED" = "GET_PLAYER_FAILED";
export const DELETE_PLAYER_REQUEST: "DELETE_PLAYER_REQUEST" =
  "DELETE_PLAYER_REQUEST";
export const DELETE_PLAYER_SUCCESS: "DELETE_PLAYER_SUCCESS" =
  "DELETE_PLAYER_SUCCESS";
export const DELETE_PLAYER_FAILED: "DELETE_PLAYER_FAILED" =
  "DELETE_PLAYER_FAILED";
export const SET_CURRENT_PLAYER_ID: "SET_CURRENT_PLAYER_ID" =
  "SET_CURRENT_PLAYER_ID";
export const SET_ACCEPT_DELETE_OPEN: "SET_ACCEPT_DELETE_OPEN" =
  "SET_ACCEPT_DELETE_OPEN";
export const SET_CONFIRM_DELETE_OPEN: "SET_CONFIRM_DELETE_OPEN" =
  "SET_CONFIRM_DELETE_OPEN";
export const SET_CONTEXT_MENU_OPEN: "SET_CONTEXT_MENU_OPEN" =
  "SET_CONTEXT_MENU_OPEN";
