export const SET_MODAL_OPEN: "SET_MODAL_OPEN" = "SET_MODAL_OPEN";
export const SET_CONTEXT_MENU_OPEN: "SET_CONTEXT_MENU_OPEN" =
  "SET_CONTEXT_MENU_OPEN";
export const SET_CONTEXT_MENU_CLOSE: "SET_CONTEXT_MENU_CLOSE" =
  "SET_CONTEXT_MENU_CLOSE";

export const SET_GENDER: "SET_GENDER" = "SET_GENDER";
export const SET_AGE: "SET_AGE" = "SET_AGE";
export const SET_SUBJECT_RF: "SET_SUBJECT_RF" = "SET_SUBJECT_RF";
export const SET_NAME: "SET_NAME" = "SET_NAME";
export const APPLY_FILTERS: "APPLY_FILTERS" = "APPLY_FILTERS";
export const DELETE_FILTER: "DELETE_FILTER" = "DELETE_FILTER";
export const CLEAR_FILTERS: "CLEAR_FILTERS" = "CLEAR_FILTERS";

export const GET_PLAYERS_REQUEST: "GET_PLAYERS_REQUEST" = "GET_PLAYERS_REQUEST";
export const GET_PLAYERS_SUCCESS: "GET_PLAYERS_SUCCESS" = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_FAILED: "GET_PLAYERS_FAILED" = "GET_PLAYERS_FAILED";

export const GET_PLAYER_REQUEST: "GET_PLAYER_REQUEST" = "GET_PLAYER_REQUEST";
export const GET_PLAYER_SUCCESS: "GET_PLAYER_SUCCESS" = "GET_PLAYER_SUCCESS";
export const GET_PLAYER_FAILED: "GET_PLAYER_FAILED" = "GET_PLAYER_FAILED";
